#!/bin/bash
: << !
<_describe> begin
描述: 工作机3022端口转发到自己笔记本,参数笔记本ip
<_describe> end
<_get_options> begin
短选项(-*):  
长选项(--*): 
其他选项: 
<_get_options> end
!
#<user_func> 
#<main>

ssh -f -N  -L 3022:192.168.1.12:3022 hik@$1