#!/bin/bash
: << !
<_describe> begin
描述: 
<_describe> end
<_get_options> begin
短选项(-*):  
长选项(--*): 
其他选项: 
<_get_options> end
!
#<user_func> 
db=''
#<main>
findso=(*.so)
for (( i =0;i< ${#findso[@]};i++ ))
do
 echo   `readelf -s ${findso[i]} | grep "$1"`
done