#!/bin/bash
: << !
<_describe> begin
描述: 
<_describe> end
<_get_options> begin
选项: 
<_get_options> end
!
#<user_func> 
#<main>
DIRPATH="/home/hik/ws/android/out/target/product/venus"
# echo $*
if [[ "$1" == "" ]];then
  adb push ${DIRPATH}/system/lib/libsensor.so /system/lib/
  adb push ${DIRPATH}/system/lib64/libsensor.so /system/lib64/

  adb push ${DIRPATH}/system/lib/libsensorservice.so /system/lib/
  adb push ${DIRPATH}/system/lib64/libsensorservice.so /system/lib64/
else
  for target_so in $*;do
    adb push ${DIRPATH}/system/lib/${target_so} /system/lib/
    adb push ${DIRPATH}/system/lib64/${target_so} /system/lib64/
  done
fi