#!/bin/bash
: << !
<_describe> begin
描述: 测试
<_describe> end
<_get_options> begin
短选项(-*): -m -d
长选项(--*): --sas
其他选项: 
<_get_options> end
!
#<user_func> 
tes() {
  echo "tessssst"
}

#<main>
echo "测试"
tes

