#!/bin/bash
: << !
<_describe> begin
描述: 测试
<_describe> end
<_get_options> begin
短选项(-*): -m -d -w -g
长选项(--*): --sas --sagde DSFDS
其他选项: 
asasd sasd  sdfss --js :da,sss:sad
<_get_options> end
!
#<user_func> 
tes() {
  echo "tessssst"
}

        #<main>
echo "dasd"
        echo $*


