#!/usr/bin/python3
import os
import sys
root_dir = os.getenv('HIK_SCRIPT_TOP_DIR')
sys.path.append(root_dir)
import hikrun
# python3 /home/hik/script/hikrun.py $*

if __name__ == '__main__':
    hikrun.main()